on:
  push:
  
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
    -
      run: |
        dotnet clean --nologo -v m
        dotnet restore --nologo -v m
        dotnet build --nologo -v m --no-restore
        dotnet test --no-build --no-restore
        dotnet run --no-build --no-restore
