on: 
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+.[0-9]+
     
jobs:
  create-release:
    name: Create Release from Tag
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout Code
      uses: actions/checkout@v3
    - 
      name: Get path tag
      id: get_tag_path
      run: |
        git_tag_url=`jq --raw-output .repository.git_tags_url ${{ github.event_path }}`
        git_tag_sha=`jq --raw-output .after                   ${{ github.event_path }}`

        git_tag_path=${git_tag_url/\{\/sha\}/\/$git_tag_sha}
        echo $git_tag_path        
        echo "::set-output name=git_tag_path::$git_tag_path"
    - 
      name: Create Release
      run: |
        message="`gh api ${{ steps.get_tag_path.outputs.git_tag_path }} | jq --raw-output .message`"
        echo -e "$message"
        gh release create ${{ github.ref_name }} --draft --title "Release ${{ github.ref_name }}" --generate-notes --notes "## $(date +%m/%d/%Y)$(echo -e "\n$message")"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
