on:
  push:
  
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout Code
      uses: actions/checkout@v3
    - 
      name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
    - 
      name: Build App
      run: |
        dotnet clean --nologo -v m
        dotnet restore --nologo -v m
        dotnet build --nologo -v m --no-restore
        dotnet test --no-build --no-restore
    - 
      name: Run App
      run: |
        dotnet run --no-build --no-restore -- ${{ github.event_path }}
