on: 
  push:
    # tags:
    # - v[0-9]+.[0-9]+.[0-9]+.[0-9]+
     
jobs:
  create-release:
    name: Create Release from Tag
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout Code
      uses: actions/checkout@v3
    -
      name: Contexts
      run: |
        echo '${{ github.event_name }}'
        echo '${{ toJSON(github.event) }}'
        echo '${{ github.job }}'
        echo '${{ github.sha }}'
        echo '${{ github.ref }}'
        echo '${{ github.ref_name }}'
        echo '${{ github.ref_protected }}'
        echo '${{ github.ref_type }}'
    - name: Get event_path info
      id: get_event_path
      run: |
        git_tags_url=`jq --raw-output .repository.git_tags_url ${{ github.event_path }}`
        sha=`jq --raw-output .after ${{ github.event_path }}`
        url=${git_tag_url/\{\/sha\}/\/$sha}
        echo $url
        echo "::set-output name=tag_url::$url"
    - name: Display event_path info
      run: |
        echo '${{ steps.get_event_path.outputs.tag_url }}'
    # echo '${{ steps.get_event_path.outputs.json_data.reposity }}'
    # echo '${{ steps.get_event_path.outputs.json_data.reposity.git_tags_url }}'
    # - name: Get tag info
    #   id: get_tag_info
    #   run: |
    #     contnet=`gh api repos/${{ github.repository }}/git/tags/${{ github.event.after }}`
    #     echo "::set-output name=json_data::$content"

    # - name: Create release
    #   run: |
    #     gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --generate-notes
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - 
    #   name: Setup .NET Core SDK
    #   uses: actions/setup-dotnet@v2.1.0
    # - 
    #   name: Build App
    #   run: |
    #     dotnet clean --nologo -v m
    #     dotnet restore --nologo -v m
    #     dotnet build --nologo -v m --no-restore
    #     dotnet test --no-build --no-restore
    # - 
    #   name: Run App
    #   run: |
    #     dotnet run --no-build --no-restore -- ${{ github.event_path }}
